### ISSUE TITLE
Trouble with refitting functions

### ISSUE THREAD

**Issue by AZlaserchron** [CIRDLES/ET_Redux#102]
While refitting individual functions for FC reference materials I was running into issues when I would try and manually adjust the y-intercept. It would move and adjust how I wanted, but as soon as I would go to the next FC and open the local fit functions the y-intercept for the very last FC I worked on reverted to its original value. If we could make it so the y-intercept after it is changed would lock that new value instead of changing every time a different analysis is updated. Would greatly make fitting functions less frustrating.

-DA

**Comment by noahmclean** [comment]
DA,

That's actually how we designed the sliders to work.  They are intended to be sensitivity tests for data exploration, so that you can see how much a date will change inside the noise/uncertainty from its fits, and better understand the limits of your measurements.  The sliders are designed to snap back to the real fit when you're done with it, and there will be no memory of your sensitivity tests.  Every bit as important as a date you've measured is its uncertainty -- hopefully this will show you what the fit to your data would look like if for instance you forced it to give you a date at the boundary of its 2-sigma uncertainty.  Also, there's no way to propagate an uncertainty for a user's arbitrary or 'eyeballed' choice in fits from the data.

The bad fits you're noticing are because we're treating 'analog mode' data just like 'pulse counter' mode for the Element 2 SEM.  We're working on both an empirical fix using data from the sessions you've sent, and hopefully a more complete fix using information from Thermo and MasCom, who make the mass spec and SEM.
