### ISSUE TITLE
New to ET-REDUX - need help

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/ET_Redux#164]
I am unable to enter a fraction mass less than 0.00001g, or rather I can enter in a smaller value but when I return to "Manage Sample" it has reverted to 0.00000.  Is there a trick?

Also, is there a way to order the fractions in the ID-TIMS workflow manager.  The fractions are ordered numerically in ET-Redux sample screen but in the order that I input the fractions in the workflow manager.  I would like them both to be numerically sorted.

**Comment by ryanfrazer** [comment]
Hi Nicole - this is a bug I have run into in the past as well. My experience with it is similar to yours. Since zircons usually weigh much less than 0.00001 g, the Manage Sample window will always round them down or up (if it's a big zircon) to that fifth decimal place.

However, the values you originally enter (the proper values, that is) are indeed stored and used by Redux in its calculations of concentrations, etc., as long as you don't re-open the Manage Sample window. So my typical workflow on a sample will be to enter the accurate zircon weights as I go, and if I do multiple rounds of analyses on a sample, I am aware that the previous weights might get wiped out as I reopen the Manage Sample window, resulting in erroneous concentrations for those earlier fractions.

When I am completely finished working on a sample (no more fractions to add or modify), I will go back to the Manage Sample window, re-enter the proper weight for each fraction, save it, and hit the "Update Data" button to get the correct concentrations calculated. I hope this helps!

**Comment by NicoleRayner** [comment]
Hi Ryan, 
Thanks - that does help, if nothing else I will stop pulling my hair out assuming it was newbie user error.

**Comment by bowring** [comment]
Thanks for bringing this to my attention so that it can be addressed!

**Comment by noahmclean** [comment]
Ah, I didn't know that anyone estimated the fraction masses!  Do you measure grain dimensions, estimate volume, then multiply by density?

**Comment by NicoleRayner** [comment]
Yep.  We use an add-in in Photoshop to "measure" the length and width and then we estimate the depth as a proportion of the width (usually 0.8).  Do you not use the fraction weight in ETREDUX at all Noah?  Or are you able to import this information from another table? Or are you using some other data reduction platform?

**Comment by ryanfrazer** [comment]
This is probably because of the old days from Drew, but at UNC we estimated x(=y) and z lengths and used the ol' zircon calculator in PbMacDat to estimate weight. Obviously the assumption of it being a whole, coherent zircon is violated by chemical abrasion, but that's what we did to get rough estimates of [U].

**Comment by noahmclean** [comment]
Got it!  I used to measure the zircon grain dimensions, also back in the good old days with Drew.  When we moved to chemical abrasion in Sam's lab, we stopped trying, though.  We figured we didn't know the proportion of zircon missing and the uranium concentration in the missing volume.  Maybe a good argument for Archean grains that turn into shards and rubble, but not the Cenozoic grains that just seem to get all polished up and shiny during leaching.  Anyway, I've been operating without concentrations for a long time but should probably rethink my approach.

What if we change the units to milligrams or better yet micrograms?  Would that fix the input problems and also keep you all from having to count zeros after the decimal?

Thanks for pointing out the problem!

**Comment by ryanfrazer** [comment]
I think switching from grams to a smaller unit would be really helpful. Micrograms make sense to me, but milligrams would be fine, too. It will certainly be more useful for people who are using the fraction weights for non-zircon minerals, too, and don’t have to worry about the fidelity of abraded grains.

This makes me think I should really comment about Redux bugs more often...

**Comment by noahmclean** [comment]
Yes -- more Redux bugs/suggestions/ideas are totally welcome!  I'll try and keep my eye on this as well so you get a prompt reply, and I'll work with Jim to get the units switched over to micrograms.  The way Jim works with units -- for instance, storing all dates as 'years' and then serving them back up as 'Ma' or 'ka' as needed -- should hopefully make this an easy lift.

**Comment by nwodicka** [comment]
Hi,
I noticed that the “fraction mass” bug is still an issue in the latest version of ET_Redux (3.6.84). I also think it would be very useful to switch the units over to micrograms (or use scientific notation), primarily to avoid having to re-enter masses when we need to re-open the Manage Sample window for whatever reason.
