### ISSUE TITLE
What are acceptable U ICs for ID-TIMS?

### ISSUE THREAD

**Issue by ryanickert** [CIRDLES/ET_Redux#175]
I'm starting to use ET-REDUX for reducing U-Pb ID-TIMS data from Sector-54 .dat files, and it's not clear what range of acceptable formats it will accept.  Right now the data are just single-U spiked with 235U, so there are no on-line fractionation corrections or oxide corrections necessary.  It appears that my "legacy" data - which consists of two ratios labelled 267/270_L1 and 267/270_L2  don't play nicely, but neither does only one ratio labelled 267/270.  After changing the file output to 238/235 it started to work.  Is there a way to find out in advance what the acceptable range of inputs are?  For the old Sector software, I only get one shot at naming the ratios, unless I want to go in an re-write dozens of old text files.  (Also, is there any way for me to import my "legacy" uranium data?  I'd love to be able to have everything we produced in the last couple months on ET-REDUX.  All it is is a single ratio and a single uncertainty!)

**Comment by bowring** [comment]
Generally, folks run Sector-54 data through Tripoli for export to ET_Redux.  @noahmclean or Blair Schoene can give you the details.  If you have already-reduced data you want to import as legacy data, we can make a template that fits your requirements.

**Comment by bowring** [comment]
Generally, folks run Sector-54 data through Tripoli for export to ET_Redux.  @noahmclean or Blair Schoene can give you the details.  If you have already-reduced data you want to import as legacy data, we can make a template that fits your requirements.

**Comment by bowring** [comment]
@ryanickert - have you gotten the answers you need?  If not, send me some example files and we will work something out.

**Comment by ryanickert** [comment]
Hi Jim.  Not really.  We were able to work out how to manually import data that we inverted, and that covers the legacy data.  I was able to work out by trial-and-error what ratios I could Tripolize and then import into ET-Redux, but what I'd prefer is to know _in advance_ what ratios it will accept.  I could give you a file now and we could work something out, but that only works for that use-case.  If I know the range of acceptable ratio-names ahead of time, I can tailor the data output to accommodate, which is a lot less work for both of us.

**Comment by bowring** [comment]
here you go:

```xml
<xs:simpleType name="MeasuredRatioNameType" >
        <xs:restriction base="xs:string" >
            <xs:enumeration value="206_204" />
            <xs:enumeration value="207_204" />
            <xs:enumeration value="208_204" />
            <xs:enumeration value="206_207" />
            <xs:enumeration value="206_208" />
            <xs:enumeration value="206_238" />
            <xs:enumeration value="204_205" />
            <xs:enumeration value="206_205" />
            <xs:enumeration value="207_205" />
            <xs:enumeration value="208_205" />
            <xs:enumeration value="208_232" />
            <xs:enumeration value="202_205" />
            <xs:enumeration value="238_236" />
            <xs:enumeration value="233_236" />
            <xs:enumeration value="238_235" />
            <xs:enumeration value="233_235" />
            <xs:enumeration value="238_233" />
        </xs:restriction>
    </xs:simpleType>
```

**Comment by noahmclean** [comment]
Hi @ryanickert, sorry I just saw this.  A couple notes:
For ID-TIMS, the ratios you need to provide Redux varies by the tracer you're using.

For a 205Pb tracer, you need to supply ALL of
206/204, 207/204, 208/204, 206/207, 206/208, 204/205, 206/205, 207/205, 208/205 (nine ratios total).  

The values of the ratios with 205 in the denominator get used for data reduction -- isotope dilution, blank correction, etc.  The uncertainties in these ratios get used for uncertainty propagation, and the uncertainties in the other five ratios (206/204, 207/204, etc) get used to calculate the uncertainty correlations between the ratios with 205 in the denominator.  So, for instance, the uncertainty in the 206/204 is used to calculate the uncertainty correlation between the 206/205 and 204/205.  

This approach (using a third ratio to calculate the covariance between two others) is outlined in the Schmitz and Shoene and Mclean et al. data reduction papers, and appears in Ludwigian software often.  It is faulty for a number of reasons.  Since U-Pb TIMS data is usually beam interpolated, each isotope ratio is calculated at a different time in the cycle -- if you multiply the first cycle's 206/204 by the 204/205, you do not get the first cycle's 206/205.  Also, TIMS users often toss out "bad blocks" of data for instance if they've been affected by isobaric interferences.  This means that the uncertainties (standard errors) used to calculate the uncertainty correlation have different n -- for instance, fewer 206/204 and 204/205 ratios than 206/205 ratios because of a block of isobaric interferences on 204Pb.  If the ratios have different n, it's easy to calculate correlation coefficients outside of the interval [-1, 1] where they belong, resulting for instance in negative or highly inflated uncertainties.  I blame this all on Ken, Mark, and Blair, it's definitely all their fault.  Another upshot is that if you don't reduce all nine of those ratios in Tripoli, then Tripoli will send a zero value and zero uncertainty to Redux for the ones you skipped.  Those zero uncertainties will blow up the uncertainty correlations among the measure isotope ratios, and therefore the uncertainties in the dates.  

After all that, for a 202Pb-205Pb tracer, you only need to send Tripoli the ratios to 205: 202/205, 203/205 (optional), 204/205, 206/205, 207/205, and 208/205.  Tripoli will see the 202/205, understand that you're using a 202Pb-205Pb tracer, and then calculate the other ratios (206/204, 207/204, 208/204, 206/207, 206/208) for you.  We did this because the 'Single' methods on the Sector 54 can only output nine ratios at a time.  Modern platforms like the Phoenix and Triton will let you output as many ratios as you like.

If you're in doubt about how those correlation coefficients are shaking out, you can always look at the Kwiki tab for your fraction (U-Pb analysis in Redux speak).  If the box of Pb ratios next to the sliders has turned pink, that's the signal that you have out-of-range correlation coefficients (there are other ways to tell, too).  Hover your mouse over the pink box to see which pair(s) of ratios is/are affected and how bad.  To get them back in range, you can go back to Tripoli and reject/accept a different set of cycles for the non-205 ratios (e.g. 206/204), Save/Export, and then watch the Kwiki window update.  I know this is a terrible way of doing things, but the difficulty is deep down (beam interpolation, the way we calculate uncertainty correlations from our data) so we submitted a proposal to the NSF five months ago to fix this, among other problems.  Fingers crossed it comes through!

**Comment by ryanickert** [comment]
Hi Noah.  My question was not quite as deep - I just wanted to know what uranium ratios it would accept, becasue my first couple stabs at it were rejected and the documentation is a bit sparse.  I'm aware of all the other issues, though it's good to know that Redux uses the covariance structure of the measured Pb ICs - it wasn't clear to me that it did so.  (I'm surpised to learn that folks reduce data by only eliminating outliers from some isotope ratios and not all!)
