### ISSUE TITLE
Distinguishing between fractions with or with no initial Pb in .xml files

### ISSUE THREAD

**Issue by nwodicka** [CIRDLES/ET_Redux#221]
In .xml files generated from the “Save and Export Aliquot as local XML file” button in the Aliquot Manager, could an entry be added to indicate whether the “No I-Pb” box in the Aliquot Manager was checked or not? 

![image](https://user-images.githubusercontent.com/47010973/200864100-7e06c96d-cff9-4df2-968d-54fc4360a737.png)

For example, the new entry could be “true” or “false” for "noInitialPb" under "AnalysisFraction" in the .xml file. This would allow us to more readily determine whether a common Pb correction was done or not for a given fraction in our database.

[Batch 1600.zip](https://github.com/CIRDLES/ET_Redux/files/9972221/Batch.1600.zip)

**Comment by noahmclean** [comment]
Hi @nwodicka , that information is actually in the xml file! When we first added the "no initial Pb" option, we called it "zircon mode" since it's an assumption we often make about zircons.  The xml tag you're looking for is "zircon," it appears near the fractionID, grainID, timestamp info for the fraction, and it's a boolean.  In the xml you provided for fraction 01FF, zircon is false, which means is the same as "No I-Pb" unchecked, and a correction will be made for initial Pbc.  

Sorry for the slow response!  If you need a quicker reply, please feel free to email me directly!

<img width="350" alt="Screen Shot 2022-12-19 at 3 26 03 PM" src="https://user-images.githubusercontent.com/7665736/208527245-9eebb4e3-da2e-43c9-b1f8-c8d41b23a94c.png">

**Comment by bowring** [comment]
I am closing this.  Thanks for your input!
